/** Exercise the real Web composition against the explicitly local CPU test provider. */
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { createServer } from 'node:net'
import { chromium, expect as baseExpect } from '@playwright/test'
import { command, launchProfile, openAspera, removeTestDirectory } from './test-app.mjs'

import { fixtureOptions, fixtureProvider } from './fixtures/models.mjs'

const root = resolve(import.meta.dirname, '..')
const expect = baseExpect.configure({ timeout: 40000 })
// Fresh published DSH profiles have measured 128 s cold starts on Windows; readiness still requires the profile's own signal.
const profileStartupMs = 180000
mkdirSync(resolve(root, '.artifacts'), { recursive: true })
const directory = mkdtempSync(resolve(root, '.artifacts/web-test-'))
const home = resolve(directory, 'home')
const portReservation = createServer()
await new Promise((ready, reject) => { portReservation.once('error', reject); portReservation.listen(0, '127.0.0.1', ready) })
const mappedPort = portReservation.address().port
await new Promise(done => { portReservation.close(done) })
const externalUrl = `http://127.0.0.1:${mappedPort}`
await command(process.execPath, ['scripts/setup.mjs'], root, { ASPERA_HOME: home })
const profile = resolve(home, 'profiles/aspera')
writeFileSync(resolve(profile, 'cordis.patch.yml'), JSON.stringify([
  { id: 'hmr', disabled: true },
  { id: 'client-hmr', disabled: true },
  { id: 'aspera-dispatch', disabled: true },
  { id: 'aspera-console', config: { pollIntervalMs: 500 } },
  { id: 'llm-pi-ai', config: { providers: { [fixtureProvider]: fixtureOptions } } },
  { id: 'agent-default-model', config: { provider: fixtureProvider, model: 'qwen-preparation' } },
  { insert: [{ id: 'aspera-test-fixture', name: pathToFileURL(resolve(root, 'scripts/fixtures/web.mjs')).href,
    config: { role: 'web', root: resolve(directory, 'remote'), release: root, profileStartupMs } }] },
]))
let app; let browser; let page
try {
  app = await launchProfile(root, home, 'aspera', {}, profileStartupMs)
  browser = await chromium.launch({ ...(process.env.ASPERA_BROWSER_EXECUTABLE ? { executablePath: process.env.ASPERA_BROWSER_EXECUTABLE } : { channel: process.env.ASPERA_BROWSER_CHANNEL || 'chrome' }), headless: true })
  const context = await browser.newContext({ acceptDownloads: true })
  const errors = []
  context.on('page', opened => {
    opened.on('pageerror', error => { errors.push(error.message); console.error('Browser exception:', error.message) })
    opened.on('console', message => { if (message.type() === 'error') console.error('Browser:', message.text()) })
  })
  page = await context.newPage()
  await openAspera(page, app.url)
  const group = () => page.getByRole('button', { name: 'Aspera', exact: true })
  await group().click()
  await expect(page.getByRole('button', { name: /^(服务器|Servers)$/ })).toHaveCount(0)
  await page.reload()
  await expect(group()).toHaveAttribute('aria-expanded', 'false')
  await group().click()
  await page.getByRole('button', { name: /Aspera 模型设置|Aspera model settings/ }).click()
  await expect(page.getByRole('dialog')).toContainText(/Aspera 模型设置|Aspera model settings/)
  await page.getByRole('button', { name: /管理模型 API|Manage model APIs/ }).click()
  await expect(page.getByRole('dialog')).toContainText(/模型|Models/)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /^(插件|Plugins)$/ }).click()
  await expect(page.getByRole('button', { name: /添加插件|Add plugin/ })).toBeEnabled()
  await page.getByText(/^(新会话|New session)$/).first().click()
  await expect(page.getByRole('heading', { name: /^(实验|Experiments)$/ })).toHaveCount(0)
  await page.getByRole('button', { name: /^(实验|Experiments)$/ }).click()
  await page.getByRole('button', { name: /^(服务器|Servers)$/ }).click()
  for (const name of ['CPU A', 'CPU B']) {
    await page.getByRole('button', { name: /^(添加服务器|Add server)$/ }).click()
    await page.locator('input[name=name]').fill(name)
    await page.locator('input[name=host]').fill(name === 'CPU A' ? 'cpu-a.test' : 'cpu-b.test')
    await page.locator('input[name=username]').fill('trainer')
    await page.locator('input[name=password]').fill('test-fixture-password')
    await expect(page.locator('input[name=remoteRoot]')).toHaveCount(0)
    if (name === 'CPU A') await page.screenshot({ path: resolve(root, '.artifacts/web-server-basic.png'), fullPage: true })
    if (name === 'CPU A') {
      await page.getByText(/推理服务对外访问（可选）|External inference access \(optional\)/, { exact: true }).click()
      await page.locator('input[name=inferenceUrl]').fill(externalUrl)
      await page.locator('input[name=inferencePort]').fill(String(mappedPort))
      await page.locator('summary').filter({ hasText: /高级设置|Advanced settings/ }).click()
      const dialogBounds = await page.getByRole('dialog').evaluate(element => {
        const bounds = element.getBoundingClientRect()
        return { top: bounds.top, bottom: bounds.bottom, viewport: innerHeight }
      })
      assert.ok(dialogBounds.top >= 0 && dialogBounds.bottom <= dialogBounds.viewport, 'Expanded server settings must fit the browser window')
      const save = page.getByRole('button', { name: /^(保存服务器|Save server)$/ })
      await save.scrollIntoViewIfNeeded()
      await expect(save).toBeInViewport()
      await page.screenshot({ path: resolve(root, '.artifacts/web-server-inference.png'), fullPage: true })
    }
    await page.getByRole('button', { name: /^(保存服务器|Save server)$/ }).click()
    await expect(page.getByRole('heading', { name: new RegExp(name) })).toBeVisible()
  }
  async function create(goal, server, mode = 'automatic', upload = false) {
    await page.getByRole('button', { name: /^(实验|Experiments)$/ }).click()
    await page.getByRole('button', { name: /^(新建实验|New experiment)$/ }).click()
    await page.getByLabel(/^(实验名称|Experiment name)$/).fill(goal)
    await page.getByLabel('Goal', { exact: true }).fill(goal)
    await expect(page.getByRole('button', { name: /^(准备模型|Preparation model)$/ })).toContainText('CPU Qwen preparation')
    await page.getByRole('button', { name: /^(计划模型|Planning model)$/ }).click()
    await page.getByRole('menuitem', { name: /CPU Qwen planning/ }).click()
    await page.getByRole('button', { name: /^(执行模型|Execution model)$/ }).click()
    await page.getByRole('menuitem', { name: /CPU Qwen execution/ }).click()
    await page.getByRole('checkbox', { name: new RegExp(server) }).check()
    if (mode === 'semi') await page.getByRole('button', { name: /半自动执行|Semi-automatic/ }).click()
    if (upload) await page.locator('input[name=uploads]').setInputFiles({ name: 'data.txt', mimeType: 'text/plain', buffer: Buffer.from('dataset') })
    await page.getByRole('button', { name: /^(提交实验|Submit experiment)$/ }).click()
    await expect(page.getByRole('heading', { name: goal, exact: true })).toBeVisible()
    await expect(page.getByText('本机派发完成，远端实验已接管', { exact: true })).toBeVisible()
  }
  const control = async (action = 'status', id) => {
    const response = await page.request.get(new URL(`/aspera-test/${action}${id === undefined ? '' : '?id=' + id}`, app.url).href)
    assert.equal(response.status(), 200)
    return response.json()
  }
  await page.getByRole('button', { name: /^(检查连接|Check connection)$/ }).first().click()
  await expect(page.getByText(/CPU test provider/, { exact: true }).first()).toBeVisible()
  assert.deepEqual((await control()).storageCalls, [], 'Connection checks must not call a model')
  await page.getByText(/磁盘与网络信息|Disk and network observations/, { exact: true }).first().click()
  await page.screenshot({ path: resolve(root, '.artifacts/web-storage-inventory.png'), fullPage: true })
  await create('CPU semi experiment', 'CPU A', 'semi', true)
  await expect(page.getByRole('button', { name: /^(确认此计划|Confirm this plan)$/ })).toBeVisible()
  const semi = (await control()).experiments.find(row => row.request.objective === 'CPU semi experiment')
  assert.equal(semi.latest.resourcesReleased, true)
  assert.equal(semi.submission.protocol, 4)
  assert.equal(semi.submission.versions.extension, '0.1.1')
  assert.deepEqual(semi.submission.nodes[0].server.inferenceMapping, { url: externalUrl, port: mappedPort })
  assert.equal(semi.preparation.placements[0].layout, 'separated')
  assert.equal(semi.preparation.placements[0].candidate.persistence, 'unknown')
  await page.screenshot({ path: resolve(root, '.artifacts/web-storage-plan.png'), fullPage: true })
  await page.getByRole('button', { name: /^(返回|Back)$/ }).click()
  await expect(page.getByText(/首次等待计划确认时，不占用训练服务器或 GPU|Initial plan confirmation does not reserve/)).toBeVisible()
  await page.getByRole('button', { name: /关闭本次提醒|Dismiss this reminder/ }).click()
  await page.reload(); await openAspera(page, app.url)
  await expect(page.getByRole('button', { name: /关闭本次提醒|Dismiss this reminder/ })).toHaveCount(0)
  await expect(page.getByLabel(/1 个实验待处理|1 experiments need attention/)).toBeVisible()
  await create('CPU independent experiment', 'CPU B')
  await expect(page.getByRole('status')).toHaveText(/服务中|Serving/, { timeout: profileStartupMs })
  await page.getByRole('button', { name: /^(返回|Back)$/ }).click()
  await page.getByRole('button').filter({ has: page.getByText('CPU semi experiment', { exact: true }) }).click()
  await page.getByRole('button', { name: /^(确认此计划|Confirm this plan)$/ }).click()
  await expect(page.getByRole('status')).toHaveText(/服务中|Serving/, { timeout: profileStartupMs })
  await create('CPU shared experiment', 'CPU A')
  await expect(page.getByRole('status')).toHaveText(/排队中|Queued/)
  await expect(page.getByText(/等待服务器|Waiting for servers/)).toBeVisible()
  const saved = await control()
  const first = saved.experiments.find(row => row.request.objective === 'CPU semi experiment')
  const separate = saved.experiments.find(row => row.request.objective === 'CPU independent experiment')
  assert.equal(first.latest.state, 'serving')
  assert.equal(separate.latest.state, 'serving')
  assert.notEqual(first.latest.sessionId, separate.latest.sessionId)
  assert.equal(JSON.stringify(saved.experiments).includes('test-fixture-password'), false)
  await page.getByRole('button', { name: /^(返回|Back)$/ }).click()
  await page.getByRole('button').filter({ has: page.getByText('CPU semi experiment', { exact: true }) }).click()
  await page.getByRole('button', { name: /^(运行监控|Runtime monitor)$/ }).click()
  const log = () => page.getByRole('region', { name: /^(运行监控|Runtime monitor)$/ }).locator('pre').first()
  await expect(log()).toContainText('服务健康')
  await context.setOffline(true)
  await control('append', first.request.experimentId)
  await context.setOffline(false)
  await expect(log()).toContainText('断线后继续')
  await control('rotate', first.request.experimentId)
  await expect(page.getByText(/日志已轮转|log was rotated/)).toBeVisible()
  await expect(log()).toContainText('轮转后日志')
  await page.getByRole('button', { name: /^(Agent 记录|Agent records)$/ }).click()
  await page.getByRole('button', { name: /^(计划|Planning)$/ }).click()
  await page.getByRole('button', { name: /^(对话|Conversation)$/ }).click()
  await expect(page.getByText('Prepare a CPU fixture service in the experiment directory.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^(执行|Execution)$/ }).click()
  await expect(page.getByText('Run the approved CPU fixture plan.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^(轨迹|Trajectory)$/ }).click()
  await page.getByRole('listitem').filter({ hasText: 'run_experiment_command' }).click()
  await page.screenshot({ path: resolve(root, '.artifacts/web-agent-trace.png'), fullPage: true })
  await page.getByRole('button', { name: /^(原始内容|Raw content)$/ }).click()
  const inspector = page.getByRole('complementary', { name: /事件详情|Event details/ })
  assert.ok((await inspector.boundingBox()).height >= 230, 'The event inspector must retain readable height')
  await page.evaluate(() => { document.body.dataset.dsDarkTheme = '' })
  await page.screenshot({ path: resolve(root, '.artifacts/web-agent-trace-dark.png'), fullPage: true })
  await page.setViewportSize({ width: 1000, height: 760 })
  await expect(inspector).toBeInViewport()
  await page.screenshot({ path: resolve(root, '.artifacts/web-agent-trace-narrow.png'), fullPage: true })
  await page.evaluate(() => { delete document.body.dataset.dsDarkTheme })
  await page.setViewportSize({ width: 1280, height: 720 })
  await inspector.getByRole('button', { name: /^(概览|Overview)$/ }).click()
  await page.getByRole('button', { name: /查看日志|View logs/ }).click()
  await expect(page.getByRole('region', { name: /运行监控|Runtime monitor/ })).toBeVisible()
  const processOutput = page.getByRole('region', { name: /运行监控|Runtime monitor/ }).locator('pre')
  await expect(processOutput).toContainText('CPU fixture service ready')
  await page.getByRole('button', { name: /^(暂停跟随|Pause follow)$/ }).click()
  await page.getByRole('button', { name: /^(节点日志|Node logs)$/ }).click()
  await page.getByRole('menuitem', { name: 'stderr', exact: true }).click()
  await expect(processOutput).toContainText('CPU fixture diagnostic stream')
  await expect(processOutput).not.toContainText('CPU fixture service ready')
  await page.screenshot({ path: resolve(root, '.artifacts/web-process-log.png'), fullPage: true })
  await page.getByRole('button', { name: /^(输出文件|Output files)$/ }).click()
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: /^(下载|Download)$/ }).click()
  const downloaded = await downloadEvent
  assert.equal(readFileSync(await downloaded.path(), 'utf8'), 'local output\n')
  await page.getByRole('button', { name: /^(推理服务|Inference services)$/ }).last().click()
  await expect(page.getByText(/外部地址已验证|External address verified/, { exact: true })).toBeVisible()
  assert.equal((await page.request.get(externalUrl)).status(), 401)
  await page.getByRole('button', { name: /查看调用信息与密钥|Show calling information and key/ }).click()
  const keyExample = page.locator('pre').filter({ hasText: 'Authorization: Bearer' })
  await expect(keyExample).toBeVisible()
  const serviceKey = (await keyExample.innerText()).match(/Bearer ([a-f0-9]{64})/)[1]
  assert.equal(JSON.stringify(await control()).includes(serviceKey), false)
  assert.equal((await page.request.get(externalUrl, { headers: { authorization: 'Bearer ' + serviceKey } })).status(), 200)
  await page.getByRole('button', { name: /隐藏调用信息|Hide calling information/ }).click()
  await page.getByRole('button', { name: /^(通过受管理的连接访问|Access through managed connection)$/ }).click()
  await expect(page.locator('pre').last()).toContainText('CPU fixture response')
  await page.screenshot({ path: resolve(root, '.artifacts/web-service.png'), fullPage: true })
  await page.close()
  page = await context.newPage()
  await openAspera(page, app.url)
  await page.getByRole('button').filter({ has: page.getByText('CPU semi experiment', { exact: true }) }).click()
  await expect(page.getByRole('status')).toHaveText(/服务中|Serving/, { timeout: profileStartupMs })
  await page.getByRole('button', { name: /^(推理服务|Inference services)$/ }).last().click()
  await page.getByRole('button', { name: /^(停止服务|Stop service)$/ }).click()
  await expect(page.getByRole('status')).toHaveText(/已完成|Completed/)
  await expect(page.getByText(/外部访问已停止|External access stopped/, { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^(返回|Back)$/ }).click()
  await page.getByRole('button').filter({ has: page.getByText('CPU shared experiment', { exact: true }) }).click()
  await expect(page.getByRole('status')).toHaveText(/服务中|Serving/, { timeout: profileStartupMs })
  await page.getByRole('button', { name: /^(取消实验|Cancel experiment)$/ }).click()
  await expect(page.getByRole('status')).toHaveText(/已取消|Cancelled/)
  await page.getByRole('button', { name: /^(返回|Back)$/ }).click()
  await page.getByRole('button').filter({ has: page.getByText('CPU independent experiment', { exact: true }) }).click()
  await control('crash', separate.request.experimentId)
  await expect(page.getByRole('status')).toHaveText(/失败|Failed/)
  await page.getByRole('button', { name: /^(推理服务|Inference services)$/ }).last().click()
  await expect(page.getByText('CPU fixture exited unexpectedly', { exact: true })).toBeVisible()
  const crashed = (await control()).experiments.find(row => row.request.experimentId === separate.request.experimentId)
  assert.equal(crashed.latest.services.length, 1)
  assert.equal(crashed.latest.services[0].state, 'failed')
  assert.equal(crashed.latest.services[0].released, true)
  await create('CPU failure experiment', 'CPU A')
  await expect(page.getByRole('alert')).toContainText('CPU fixture dependency failed')
  await page.screenshot({ path: resolve(root, '.artifacts/web-error.png'), fullPage: true })
  await create('CPU operator question', 'CPU A', 'semi')
  await page.getByRole('button', { name: /^(确认此计划|Confirm this plan)$/ }).click()
  const questionCard = () => page.getByRole('region', { name: /需要你的决定|Your decision is needed/ })
  await expect(questionCard()).toBeVisible()
  await expect(page.getByLabel(/1 个实验待处理|1 experiments need attention/)).toBeVisible()
  const waiting = (await control()).experiments.find(row => row.request.objective === 'CPU operator question')
  await page.screenshot({ path: resolve(root, '.artifacts/web-question.png'), fullPage: true })
  await page.close(); page = await context.newPage()
  await openAspera(page, app.url)
  await page.getByRole('button', { name: /待处理|Needs attention/ }).click()
  await page.getByRole('button', { name: 'CPU operator question', exact: true }).click()
  await expect(questionCard()).toBeVisible()
  await expect(page.getByLabel(/1 个实验待处理|1 experiments need attention/)).toBeVisible()
  await questionCard().getByRole('checkbox', { name: 'Use the held-out split' }).check()
  await questionCard().getByRole('textbox').fill('Keep the specified data and server group.')
  await questionCard().getByRole('button', { name: /回复并继续|Save reply and continue/ }).click()
  await expect(questionCard()).toHaveCount(0)
  await expect(page.getByLabel(/1 个实验待处理|1 experiments need attention/)).toHaveCount(0)
  await expect(page.getByRole('status').first()).toHaveText(/服务中|Serving/, { timeout: profileStartupMs })
  const answered = (await control()).experiments.find(row => row.request.experimentId === waiting.request.experimentId)
  assert.equal(answered.latest.sessionId, waiting.latest.sessionId)
  assert.equal(answered.latest.goalId, waiting.latest.goalId)
  assert.equal(answered.latest.questions[0].state, 'answered')
  await page.getByRole('button', { name: /^(取消实验|Cancel experiment)$/ }).click()
  await expect(page.getByRole('status').first()).toHaveText(/已取消|Cancelled/)
  const final = await control()
  const dispatchEvents = final.events.filter(item => item.sessionId === first.sessionId)
  const snapshot = {
    agentModels: Object.fromEntries(Object.entries(first.models).map(([phase, model]) => [phase, { provider: model.provider, model: model.model }])),
    dispatchGoalPhases: dispatchEvents.filter(item => item.event.type === 'goal/change').map(item => item.event.data.goal?.phase),
    handover: dispatchEvents.filter(item => item.event.type === 'user/message' && item.event.data.content[0].text.startsWith('本机派发完成')).map(item => item.event.data.content[0].text.split('\n')[0]),
    storageTools: final.storageCalls.filter(item => item.experimentId === first.request.experimentId).map(item => item.name),
    storage: first.preparation.placements.map(item => ({ layout: item.layout, systemVolume: item.candidate.systemVolume, persistence: item.candidate.persistence })),
    inference: { mapped: first.submission.nodes[0].server.inferenceMapping !== undefined,
      external: first.latest.services[0].external.state, modelName: first.latest.services[0].modelName,
      stopped: final.experiments.find(row => row.request.experimentId === first.request.experimentId).latest.services[0].external.state },
    receiptStates: final.experiments.filter(row => ['CPU semi experiment', 'CPU shared experiment', 'CPU failure experiment'].includes(row.request.objective))
      .sort((a, b) => a.request.objective.localeCompare(b.request.objective)).map(row => ({ goal: row.request.objective, handover: row.receipt.handover, state: row.latest.state })),
  }
  const expected = JSON.parse(readFileSync(resolve(root, 'scripts/fixtures/session.snapshot.json'), 'utf8'))
  assert.deepEqual(snapshot, expected)
  assert.deepEqual(errors, [])
  console.log('Real Web: servers/passwords, attachments, independent Goals, plan confirmation, parallelism/queue, handover Session snapshot, UTF-8/reconnect/rotation, download, service access/survival/stop/unexpected exit, cancellation and errors passed.')
} catch (error) {
  if (page !== undefined && !page.isClosed()) {
    await page.screenshot({ path: resolve(root, '.artifacts/web-failure.png'), fullPage: true })
    console.error((await page.locator('body').innerText()).slice(-5000))
    console.error((await page.locator('details').allTextContents()).map(value => value.slice(0, 1000)))
  }
  console.error('Web test profile tail: ' + (app?.output() ?? '').replace(/token=[A-Za-z0-9_-]+/g, 'token=<redacted>').slice(-7000))
  throw error
} finally {
  await browser?.close(); await app?.close()
  removeTestDirectory(directory, resolve(root, '.artifacts'))
}
